services:
  postgres_plnim:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: plnim-test
    container_name: plnim_container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5445:5432"
